# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-27 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20190128_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='media/avatars/default.png', upload_to='avatars/', verbose_name='头像'),
        ),
    ]
